# Site settings
title:            赵达的个人网站 - Zhao Da's Personal Website
name:             赵达
email:            zd6437@gmail.com
description:      我目前就职于腾讯，是一名高级前端开发工程师。
baseurl:          ""
url:              http://zhaoda.net
twitter_username: sage6437
github_username:  zhaoda
github_url:       https://github.com/zhaoda/zhaoda.github.io
lang:             zh
timezone:         Asia/Shanghai
google_verify:    k9Sobn7a9wwRvlG0YV0L8f2wiguGMDSUNaqlgQd46Ro
google_plus:      113279817760268675586

# Handling Reading
safe:         false
encoding:     "utf-8"
permalink:    pretty

sass:
    style: :compressed

gems:
    - jekyll-sitemap
    - jekyll-feed

exclude: ["README.md"]

# Default layout
defaults:
  -
    scope:
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      type: "posts"
    values:
      layout: "post"

# Conversion
highlighter: pygments

markdown: redcarpet
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - lax_spacing
    - fenced_code_blocks
    - tables

# markdown: kramdown
# kramdown:
#   input:         GFM
#   auto_ids:      true
#   auto_id_prefix: 'id-'

excerpt_separator: "<!--more-->"




